language:
  - python
python:
  - "2.6"
  - "2.7"
  # - "3.2"
  # - "3.3"
before_install:
  - sudo apt-get install -qq python-numpy python-scipy
install:
  - pip install nose --use-mirrors
  - python setup.py install
script:
  - nosetests tests
