language:
  - python
python:
  - "2.6"
  - "2.7"
  # - "3.2"
  # - "3.3"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-numpy python-scipy
install:
  - pip install nose scipy --use-mirrors
  - python setup.py install
script:
  - nosetests tests
