language:
  - python
python:
  # https://github.com/travis-ci/travis-ci/issues/2219#issuecomment-41804942
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  # download NLTK corpora manually - https://github.com/nltk/nltk/issues/565
  - wget https://s3.amazonaws.com/textblob/nltk_data.tar.gz
  - tar -xzvf nltk_data.tar.gz -C ~
  # install dependencies for NumPy
  - sudo apt-get update -qq
  - sudo apt-get install -qq gfortran libatlas-base-dev
  - sudo apt-get install -qq python-numpy
install:
  - python setup.py install
  - pip install -U pip wheel
  - pip install -U --use-wheel pytest pytest-cov
  # - python -c "import nltk; nltk.download('punkt')"
script:
  - py.test tests
