language:
  - python
python:
  - "2.6"
  - "2.7"
  # - "3.2"
  # - "3.3"
virtualenv:
  system_site_packages: true
before_install:
  # download NLTK corpora manually - https://github.com/nltk/nltk/issues/565
  - wget https://s3.amazonaws.com/textblob/nltk_data.tar.gz
  - tar -xzvf nltk_data.tar.gz -C ~
  # install dependencies for NumPy
  - sudo apt-get update -qq
  - sudo apt-get install -qq gfortran libatlas-base-dev
  - sudo apt-get install -qq python-numpy
install:
  - pip install nose --use-mirrors
  - pip install git+git://github.com/miso-belica/readability.py.git
  - python setup.py install
  # - python -c "import nltk; nltk.download('punkt')"
script:
  - nosetests tests
